server:
  port: 7001
eureka:
  instance:
    hostname: localhost7001
  client:
    register-with-eureka: false  #false表示不向注册中心注册自己
    fetch-registry: false    # false表示自己就是注册中心，
    service-url:
      #设置与eureka server交互的地址 查询服务和注册服务都需要依赖这个地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/